export default {
    GET_MINIFIGS_LIST                : 'GET_MINIFIGS_LIST',
    GET_MINIFIGS_DETAILED            : 'GET_MINIFIGS_DETAILED',
    START_LOADING_MINIFIGS           : 'START_LOADING_MINIFIGS',
    FINISH_LOADING_MINIFIGS          : 'FINISH_LOADING_MINIFIGS',
    START_LOADING_MINIFIGS_DETAILED  : 'START_LOADING_MINIFIGS_DETAILED',
    FINISH_LOADING_MINIFIGS_DETAILED : 'FINISH_LOADING_MINIFIGS_DETAILED',
    UPDATE_WEB_SITES_LIST            : 'UPDATE_WEB_SITES_LIST'

};
